# This file is generated by `tools/abi.R`, do not modify by hand.

#' tree-sitter ABI version
#'
#' `abi()` returns the ABI version that `parser.c` was generated with. This is
#' used to verify that the grammar is compatible with the tree-sitter C library
#' embedded within the treesitter package.
#'
#' @returns A single integer.
#'
#' @noRd
abi <- function() {
  # ABI: LANGUAGE_VERSION
  LANGUAGE_VERSIONL
}
