# https://github.com/tree-sitter/workflows/blob/main/.github/workflows/package-npm.yml

name: Publish package (npm)

on:
  workflow_call:
    inputs:
      package-name:
        description: The name of the package
        default: ${{github.event.repository.name}}
        type: string
      environment-name:
        description: The name of the environment
        default: npm
        type: string
      node-version:
        description: The NodeJS version
        default: ${{vars.NODE_VERSION || '22'}}
        type: string
      generate:
        description: Generate the parser artifacts
        default: false
        type: boolean
      abi-version:
        description: The tree-sitter ABI version
        default: 15
        type: number
    secrets:
      NODE_AUTH_TOKEN:
        description: An authentication token for npm
        required: true

defaults:
  run:
    shell: bash

jobs:
  build_wasm:
    name: Build Wasm binaries
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
      - name: Regenerate parser
        if: ${{inputs.generate}}
        run: |
          while read -r grammar_dir; do
            pushd "$grammar_dir"
            npm x -- tree-sitter generate
            popd > /dev/null
          done < <(jq -r '.grammars[].path // "."' tree-sitter.json)
        env:
          TREE_SITTER_ABI_VERSION: ${{inputs.abi-version}}
      - name: Build Wasm binaries
        run: |-
          while read -r grammar_dir; do
            npm x -- tree-sitter build --wasm "$grammar_dir"
          done < <(jq -r '.grammars[].path // "."' tree-sitter.json)
      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          path: "*.wasm"
          name: prebuilds-wasm
          retention-days: 2

  build_node:
    name: Build NodeJS binaries on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-11-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - macos-15-intel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
      - name: Regenerate parser
        if: ${{inputs.generate}}
        shell: bash
        run: |
          while read -r grammar_dir; do
            grammar_dir="${grammar_dir%$'\r'}"
            pushd "$grammar_dir"
            npm x -- tree-sitter generate
            popd > /dev/null
          done < <(jq -r '.grammars[].path // "."' tree-sitter.json)
      - name: Build binary
        run: npm x -- prebuildify -t 20.19.5
      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          path: prebuilds/**
          name: prebuilds-${{matrix.os}}
          retention-days: 2

  package:
    name: Publish NodeJS package
    needs: [build_wasm, build_node]
    runs-on: ubuntu-24.04
    environment:
      name: ${{inputs.environment-name}}
      # Changed so it uses the scoped url
      url: https://www.npmjs.com/package/@davisvaughan/${{inputs.package-name}}
      # url: https://www.npmjs.com/package/${{inputs.package-name}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
          registry-url: https://registry.npmjs.org/
      - name: Download binaries
        uses: actions/download-artifact@v8
        with:
          path: prebuilds
          pattern: prebuilds-*
          merge-multiple: true
      - name: Check binaries
        run: tree prebuilds
      - name: Move Wasm binaries to root
        continue-on-error: true
        run: mv -v prebuilds/*.wasm .
      - name: Publish to npm
        # This is the only thing we change, because we currently publish a scoped package,
        # so we need `--access public` because scoped packages are private by default (#41)
        run: npm publish --access public
        # run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
